---
DATA:
  dir: "/home/egoncalves/PhenPred/datasets"
  min_count: 100

ML:
  model: "rf"
  dataset_y: "drug_response"
  params_grid:
    criterion: ["squared_error"]
    n_estimators: [600] # [400, 600, 800, 1000]
    min_samples_split: [5] # [2, 5]
    min_samples_leaf: [2] # [1, 2]
    max_features: ["sqrt"]
    n_jobs: [-1]
  cv:
    n_splits: 5

OUTPUT:
  dir: "data/"